Fetch admin passwords from file
bitnami/bitnami-docker-openldap pull request #108
Opened 2022-06-05 17:54 UTC by Shakespeare2000

**Description of the change**

- Added common logic to fetch contents from LDAP_ADMIN_PASSWORD_FILE and LDAP_CONFIG_ADMIN_PASSWORD_FILE
- Updated README

**Benefits**

- Allows the use of the Docker Secrets functionality, to prevent unencrypted passwords to be available within environment variables of the process.

**Possible drawbacks**

Can't think of one.

**Applicable issues**

- Partially completes the features requested in https://github.com/bitnami/bitnami-docker-openldap/issues/62.
- Completes https://github.com/bitnami/bitnami-docker-openldap/pull/65

**Additional information**

The logic for fetching the contents of Docker Secret files based on [the logic used for MariaDB](https://github.com/bitnami/bitnami-docker-mariadb/blob/master/10.6/debian-10/rootfs/opt/bitnami/scripts/mariadb-env.sh).

2022-06-08 16:23 UTC, joancafom requested changes
Thanks for your PR @Shakespeare2000 ! I left you a comment, could you please review it?

2022-06-14 12:10 UTC, joancafom commented on 2.6/debian-10/rootfs/opt/bitnami/scripts/libopenldap.sh
> +
> ldap_env() does not load the global variables, the eval of $(ldap_env) does. ldap_env() just returns a string.

Well, the string itself is evaluated as code, so I reckon there shouldn't be any problems. 

> Exporting global variables within ldap_env won't work, because that function runs in a subshell ($()).

Well, the same function is already in charge of handling the exporting at the moment. It is called in every script in which those env vars are needed, before performing any action. I might be wrong, but don't think that adding more logic to the `ldap_env` will make a substantial difference:

```diff
ldap_env() {
    cat << "EOF"
# Paths
export LDAP_BASE_DIR="/opt/bitnami/openldap"
...
export LDAP_LOGLEVEL="${LDAP_LOGLEVEL:-256}"
+for env_var in "${ldap_env_vars[@]}"; do
+    file_env_var="${env_var}_FILE"
+    if [[ -n "${!file_env_var:-}" ]]; then
+        if [[ -r "${!file_env_var:-}" ]]; then
+            export "${env_var}=$(< "${!file_env_var}")"
+            unset "${file_env_var}"
+        else
+            warn "Skipping export of '${env_var}'. '${!file_env_var:-}' is not readable."
+        fi
+    fi
+done
+unset ldap_env_vars
EOF
```

2022-06-14 12:25 UTC, joancafom commented on 2.6/debian-10/rootfs/opt/bitnami/scripts/libopenldap.sh
> +
Furthermore, I did a quick test and it seems to work (the values are OK):

**docker-compose.yml**

```diff
version: '2'

services:
  openldap:
    image: my_open
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
+     - LDAP_ADMIN_PASSWORD_FILE=/tmp/abc
    volumes:
      - 'openldap_data:/bitnami/openldap'
+     - './abc:/tmp/abc'

volumes:
  openldap_data:
    driver: local
```

**rootfs/opt/bitnami/scripts/openldap/setup.sh**
```diff
#!/bin/bash
...
# Load LDAP environment variables
eval "$(ldap_env)"
+ printenv
```
----

This outputs the following:

```
Creating network "debian-11_default" with the default driver
Creating volume "debian-11_openldap_data" with local driver
Creating debian-11_openldap_1 ... done
Attaching to debian-11_openldap_1
openldap_1  |  12:13:06.84 INFO  ==> ** Starting LDAP setup **
...
openldap_1  | LDAP_ADMIN_PASSWORD=12345
```

2022-06-14 18:41 UTC, Shakespeare2000 commented on 2.6/debian-10/rootfs/opt/bitnami/scripts/libopenldap.sh
> +
Doh... of course, putting the logic inside the `cat` works.

2022-06-21 11:37 UTC, joancafom reviewed
Thanks for the changes! As this is not a trivial change, let me test it on my side and I will come back with feedback (if any) 🚀

2022-06-22 15:32 UTC, joancafom requested changes
One last kind of nitpicky request 😁.

2022-06-22 15:32 UTC, joancafom commented on README.md
> +- `LDAP_ADMIN_PASSWORD_FILE`: Path to a file that contains the LDAP database admin user password. This will override the value specified in LDAP_ADMIN_PASSWORD. No defaults.
```suggestion
- `LDAP_ADMIN_PASSWORD_FILE`: Path to a file that contains the LDAP database admin user password. This will override the value specified in `LDAP_ADMIN_PASSWORD`. No defaults.
```

2022-06-22 15:32 UTC, joancafom commented on README.md
> +- `LDAP_CONFIG_ADMIN_PASSWORD_FILE`: Path to a file that contains the LDAP configuration admin user password. This will override the value specified in LDAP_CONFIG_ADMIN_PASSWORD. No defaults.
```suggestion
- `LDAP_CONFIG_ADMIN_PASSWORD_FILE`: Path to a file that contains the LDAP configuration admin user password. This will override the value specified in `LDAP_CONFIG_ADMIN_PASSWORD`. No defaults.
```

2022-06-22 18:11 UTC, Shakespeare2000 commented
@joancafom I'm sorry for the mess 😢 (forgot to fetch the upstream changes first).
Is this still a viable PR, or should I open a new one?

2022-06-23 07:52 UTC, joancafom commented
@Shakespeare2000 don't worry, I've resolved the conflicts myself for you 😁 

Thanks for the changes 🚀

2022-06-23 07:55 UTC, joancafom approved these changes

2022-06-23 08:01 UTC, merged