Adding custom schema
bitnami/bitnami-docker-openldap pull request #12
Opened 2020-11-04 18:41 UTC by phcollignon

Adding a custom schema with some internal values  (i.e `structuralObjectClass`) in OpenLDAP cannot be achieved using `ldapadd` an ldif files afterwards.
It can only be done using `slapadd` at setup. 

This pull request allows to optionaly add such a schema.  If `LDAP_CUSTOM_SCHEMA_FILE` variable does exist and refers to an existing schema file, then the schema is added using `slapadd`

2020-11-05 09:23 UTC, miguelaeh requested changes
Hi @phcollignon ,
Thank you very much for the PR!
Please take a look at my comments

2020-11-05 09:23 UTC, miguelaeh commented on 2/debian-10/rootfs/opt/bitnami/scripts/libopenldap.sh
> +    debug_execute slapadd -F "$LDAP_ONLINE_CONF_DIR" -n 0 -l  "$LDAP_CUSTOM_SCHEMA_FILE"
```suggestion
    info "Adding custom Schema: $LDAP_CUSTOM_SCHEMA_FILE ..."
    debug_execute slapadd -F "$LDAP_ONLINE_CONF_DIR" -n 0 -l "$LDAP_CUSTOM_SCHEMA_FILE"
```

2020-11-05 09:23 UTC, miguelaeh commented on 2/debian-10/rootfs/opt/bitnami/scripts/libopenldap.sh
> +    ldap_start_bg
Why is this needed?

2020-11-05 09:23 UTC, miguelaeh commented on 2/debian-10/rootfs/opt/bitnami/scripts/libopenldap.sh
> +export LDAP_CUSTOM_SCHEMA_FILE="${LDAP_CUSTOM_SCHEMA_FILE:-/schema/custom.ldif}"
I think it would have sense to use the volume  for this custom file`LDAP_VOLUME_DIR/schema/custom.ldif`

2020-11-05 13:43 UTC, phcollignon commented on 2/debian-10/rootfs/opt/bitnami/scripts/libopenldap.sh
> +    ldap_start_bg
I had error without it .. maybe stop process was not complete, if we could avoid it or do it in a better way it would be nice indeed.

2020-11-05 13:49 UTC, phcollignon commented on 2/debian-10/rootfs/opt/bitnami/scripts/libopenldap.sh
> +export LDAP_CUSTOM_SCHEMA_FILE="${LDAP_CUSTOM_SCHEMA_FILE:-/schema/custom.ldif}"
This is the idea, it has to be mapped as a volume, (to follow same convention as for LDAP_CUSTOM_LDIF_DIR) : 
```
    volumes:
      - 'openldap_data:/bitnami/openldap'
      - ./imports/ldifs:/ldifs
      - ./imports/schema/my_schema.ldif:/schema/custom.ldif
```

2020-11-06 09:27 UTC, miguelaeh requested changes

2020-11-06 09:27 UTC, miguelaeh commented on 2/debian-10/rootfs/opt/bitnami/scripts/libopenldap.sh
> +    ldap_start_bg
At the point you are calling this function, it has already been started in background to add schemas so I think it should not be needed to stop and start it again.
See the `ldap_initialize` function:
```
ldap_initialize() {
    info "Initializing OpenLDAP..."

    ldap_configure_permissions
    if ! is_dir_empty "$LDAP_DATA_DIR"; then
        info "Using persisted data"
    else
        # Create OpenLDAP online configuration
        ldap_create_online_configuration
        ldap_start_bg
        ldap_admin_credentials
        if is_boolean_yes "$LDAP_SKIP_DEFAULT_TREE"; then
            info "Skipping default schemas/tree structure"
        else
            # Initialize OpenLDAP with schemas/tree structure
            ldap_add_schemas
<--------- You are adding your code here, it is already running --------->
            if ! is_dir_empty "$LDAP_CUSTOM_LDIF_DIR"; then
                ldap_add_custom_ldifs
            else
                ldap_create_tree
            fi
        fi
        ldap_stop
    fi
}
```

2020-11-06 15:16 UTC, phcollignon commented on 2/debian-10/rootfs/opt/bitnami/scripts/libopenldap.sh
> +    ldap_start_bg
Indeed it has already been started but It is restarted after adding the schema with `slapadd` so that the new schema are available for `ldap_add_custom_ldifs`.  I'm not LDAP expert but it was not working without any restart.

2020-11-09 13:52 UTC, phcollignon commented
Change is not required.  The server is restarted after adding the schema with slapadd so that the new schema is available for ldap_add_custom_ldifs. I'm not LDAP expert but it was not working without any restart - I mean the schema was not available.

2020-11-09 13:53 UTC, phcollignon commented
Change is not required. The server is restarted after adding the schema with slapadd so that the new schema is available for ldap_add_custom_ldifs. I'm not LDAP expert but it was not working without any restart - I mean the schema was not available.

2020-11-10 08:34 UTC, javsalgar commented on 2/debian-10/rootfs/opt/bitnami/scripts/libopenldap.sh
> +    ldap_start_bg
I have my concerns on adding an infinite loop, I would rather use a retry_while and throw an error if it was not stopped correctly. I would also add a comment explaining why this restart is necessary.

2020-11-10 08:35 UTC, javsalgar commented on 2/debian-10/rootfs/opt/bitnami/scripts/libopenldap.sh
> +export LDAP_CUSTOM_SCHEMA_FILE="${LDAP_CUSTOM_SCHEMA_FILE:-/schema/custom.ldif}"
Would there be any issue if it was `/bitnami/openldap/schema` or `/bitnmai/openldap/ldifs` the default? Just for following the same conventions in all our containers.

2020-11-10 08:35 UTC, javsalgar commented
Added some comments

2020-11-12 11:26 UTC, wiibaker commented on 2/debian-10/rootfs/opt/bitnami/scripts/libopenldap.sh
> +    debug_execute slapadd -F "$LDAP_ONLINE_CONF_DIR" -n 0 -l  "$LDAP_CUSTOM_SCHEMA_FILE"
Could that be 

```suggestion
    debug_execute for f in $LDAP_CUSTOM_SCHEMA_DIR/*.ldif; do slapadd -F "$LDAP_ONLINE_CONF_DIR" -n 0 -l $f; done
```

And that env variable to be a directory instead of just single file. In same fashion as the LDAP_CUSTOM_LDIF_DIR.

2020-11-12 11:27 UTC, wiibaker commented
I created quite a similar PR #15 before I noticed this one exists already (this was not bound to any issue). Either one will most probably work for us.

2020-11-12 20:49 UTC, phcollignon commented on 2/debian-10/rootfs/opt/bitnami/scripts/libopenldap.sh
> +export LDAP_CUSTOM_SCHEMA_FILE="${LDAP_CUSTOM_SCHEMA_FILE:-/schema/custom.ldif}"
I think it can be any directory as long as we keep it  consistent between custom schema and ldifs files

2020-11-12 20:51 UTC, phcollignon commented on 2/debian-10/rootfs/opt/bitnami/scripts/libopenldap.sh
> +    debug_execute slapadd -F "$LDAP_ONLINE_CONF_DIR" -n 0 -l  "$LDAP_CUSTOM_SCHEMA_FILE"
better indeed to support multiple custom schemas

2020-11-12 20:58 UTC, phcollignon commented
> I created quite a similar PR #15 before I noticed this one exists already (this was not bound to any issue). Either one will most probably work for us.

No problem. I just noticed that you are using `ldapadd` instead of `slapadd`.  The fact is that `ldapadd` does not work for some schema defining internal properties because it does not have enough privileges.

2020-11-12 21:04 UTC, phcollignon commented on 2/debian-10/rootfs/opt/bitnami/scripts/libopenldap.sh
> +    ldap_start_bg
Yes indeed. I'am also not happy about the code to restart the server.  If there is a better solution we should think about it.

2020-11-13 07:16 UTC, wiibaker commented
> The fact is that `ldapadd` does not work for some schema defining internal properties because it does not have enough privileges.

The LDAP is not really my specialitée :) In our case the "ldapadd" was sufficient. Which me think that would it make sense to have both options? One folder for each?

2020-11-13 08:50 UTC, javsalgar commented
Wouldn't slapadd cover both?

2020-11-23 08:41 UTC, javsalgar commented
@wiibaker could you confirm if slapadd could cover your use case?

2020-11-24 08:30 UTC, wiibaker commented
> @wiibaker could you confirm if slapadd could cover your use case?

Not able to verify just now, but I do not see any reason why "slapadd" could not do something that "ldadadd" could.

2020-11-24 09:12 UTC, javsalgar commented
Ok, thanks for the information. Then I believe we should go ahead with slapadd. @miguelaeh could you continue with the revision? I see that you suggested some changes that are still pending.

2020-11-24 10:10 UTC, miguelaeh commented on 2/debian-10/rootfs/opt/bitnami/scripts/libopenldap.sh
> +export LDAP_CUSTOM_SCHEMA_FILE="${LDAP_CUSTOM_SCHEMA_FILE:-/schema/custom.ldif}"
Then, I would prefer to use a directory like the ones that @javsalgar proposed. It will add consistency with the rest of our containers.

2021-02-23 00:04 UTC, maccimacci commented
There is any advance with this feature ? I'd like to import a custom schema.

2021-02-23 09:22 UTC, phcollignon commented
Does not seem to be merged in this project but you can use my fork if you
need to import a custom schema.

Le mar. 23 févr. 2021 à 01:05, Maximiliano Nieva <notifications@github.com>
a écrit :

> There is any advance with this feature ? I'd like to import a custom
> schema.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/bitnami/bitnami-docker-openldap/pull/12#issuecomment-783768314>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB2TEXCE4WJXY4RPVOL3OILTALWK3ANCNFSM4TKM6XKA>
> .
>

2021-02-23 09:26 UTC, phcollignon commented
No I mean `slapadd` has to be restarted for some custom schemas to be taken
into account.

Le mar. 23 févr. 2021 à 09:57, Miguel Ángel Cabrera Miñagorri <
notifications@github.com> a écrit :

> *@miguelaeh* commented on this pull request.
> ------------------------------
>
> In 2/debian-10/rootfs/opt/bitnami/scripts/libopenldap.sh
> <https://github.com/bitnami/bitnami-docker-openldap/pull/12#discussion_r529409903>
> :
>
> > +    ldap_stop
> +     while is_ldap_running; do sleep 1; done
> +    ldap_start_bg
>
> Indeed it has already been started but It is restarted after adding the
> schema with slapadd so that the new schema are available for
> ldap_add_custom_ldifs. I'm not LDAP expert but it was not working without
> any restart - I mean the schema was not available.
>
> I don't fully understand this. Do you mean that slapadd restarts the
> server?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/bitnami/bitnami-docker-openldap/pull/12#discussion_r529409903>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB2TEXHR5YRWSEEZ5BB4M43TANUWXANCNFSM4TKM6XKA>
> .
>

2021-02-24 11:18 UTC, miguelaeh approved these changes

2021-02-24 11:18 UTC, merged