Find should now follow symlinks when looking for custom LDIFs.
bitnami/bitnami-docker-openldap pull request #20
Opened 2020-12-14 10:26 UTC by Bengrunt

**Description of the change**

As per @saadlu comments in #8, this small change should help when loading LDIFs through configmaps in a Kubernetes environment as then the files are accessed via symlinks and thus find won't find them.

**Benefits**

Kubernetes deployments using configmaps for the LDIFs file will certainly benefit.

**Possible drawbacks**

Did not test this myself in a Kubernetes environment.   
Maybe @saadly could give it a look?

2020-12-15 07:59 UTC, juan131 requested changes

2020-12-15 07:59 UTC, juan131 commented on 2/debian-10/rootfs/opt/bitnami/scripts/libopenldap.sh
> +    debug_execute find "$LDAP_CUSTOM_LDIF_DIR" -maxdepth 1 -type f,l -iname '*.ldif' -print0 | sort -z | xargs --null -I{} ldapadd -f {} -H 'ldapi:///' -D "$LDAP_ADMIN_DN" -w "$LDAP_ADMIN_PASSWORD"
As I mentioned at https://github.com/bitnami/bitnami-docker-openldap/pull/8
It doesn't make much sense to pass the whole "find command" to debug_execute. Instead, we only need to run the "ldapadd command" with `debug_execute`.
This is a possible solution:
```suggestion
find "$LDAP_CUSTOM_LDIF_DIR" -maxdepth 1 -type f,l -iname '*.ldif' -print0 | sort -z | xargs --null -I{} bash -c ". /opt/bitnami/scripts/libos.sh && debug_execute ldapadd -f {} -H 'ldapi:///' -D $LDAP_ADMIN_DN -w $LDAP_ADMIN_PASSWORD"
```

2020-12-15 13:07 UTC, Bengrunt commented on 2/debian-10/rootfs/opt/bitnami/scripts/libopenldap.sh
> +    debug_execute find "$LDAP_CUSTOM_LDIF_DIR" -maxdepth 1 -type f,l -iname '*.ldif' -print0 | sort -z | xargs --null -I{} ldapadd -f {} -H 'ldapi:///' -D "$LDAP_ADMIN_DN" -w "$LDAP_ADMIN_PASSWORD"
Fair enough. That's done in my latest commit.

2020-12-15 13:07 UTC, Bengrunt commented
Carried out requested changes regarding `debug_execute` scope.

2020-12-23 15:35 UTC, marcosbc requested changes
Hi @Bengrunt, sorry for the delay. Due to holidays season we have a lot on our plate and this PR got past us.

The problem with the current approach is that RHEL-like distros (i.e. CentOS 7) don't support multiple arguments to the `-type` flag, and we try to make our logic compatible for most distros at the same time:

```
$ docker run -ti centos:7 find /tmp -type f,l
find: Arguments to -type should contain only one letter
```

If you change this:

    -type f,l

To this:

    \( -type f -o -type l \)

Then it should work for any modern distro:

```
$ docker run -ti centos:7 find /tmp \( -type f -o -type l \)
/tmp/ks-script-DrRL8A
/tmp/yum.log
```

Could you update the PR with that change?

2021-01-06 15:59 UTC, Bengrunt commented
> 
> 
> Hi @Bengrunt, sorry for the delay. Due to holidays season we have a lot on our plate and this PR got past us.
> 
> The problem with the current approach is that RHEL-like distros (i.e. CentOS 7) don't support multiple arguments to the `-type` flag, and we try to make our logic compatible for most distros at the same time:
> 
> ```
> $ docker run -ti centos:7 find /tmp -type f,l
> find: Arguments to -type should contain only one letter
> ```
> 
> If you change this:
> 
> ```
> -type f,l
> ```
> 
> To this:
> 
> ```
> \( -type f -o -type l \)
> ```
> 
> Then it should work for any modern distro:
> 
> ```
> $ docker run -ti centos:7 find /tmp \( -type f -o -type l \)
> /tmp/ks-script-DrRL8A
> /tmp/yum.log
> ```
> 
> Could you update the PR with that change?

Hello,

Sorry for the delay, took a long and well deserved time off off the internet 👍 

So I just modified my PR to include the changes you suggested.  
I didn't test them though.

2021-01-07 16:19 UTC, marcosbc approved these changes
LGTM, thanks! FYI we'll work on releasing a new Docker image for OpenLDAP with these changes, which we expect will take some hours and probably not be ready before tomorrow.

2021-01-07 16:19 UTC, merged

2021-01-08 10:25 UTC, marcosbc commented
Hi, just wanted to let you know that we released `2.4.56-debian-10-r56` which includes this fix.