Wait for LDAP process to exit after stopping.
bitnami/bitnami-docker-openldap pull request #35
Opened 2021-05-20 20:56 UTC by mattmoyer

**Description of the change**

This change updates the `ldap_stop` function to wait for the LDAP process to exit after signaling. Prior to this change, the script waited for the process to stop _or_ the PID file to be deleted.

**Benefits**

This should make the startup more reliable, eliminating the race condition documented in #1. I was able to consistently reproduce the bug locally prior to this patch. With this change, I've not seen a failure.

**Possible drawbacks**

None of which I'm aware.

**Applicable issues**

#1

**Additional information**

I also tried a simple one-line patch to add a `sleep 1`, which also worked but seemed clunkier.

2021-05-21 06:17 UTC, juan131 approved these changes
Thanks for the PR @mattmoyer 

I have a different proposal that I recently implemented in MySQL with great results, see https://github.com/bitnami/bitnami-docker-mysql/pull/130

As you can see in that PR, I improved the `mysql_stop` function including a loop that checks that every file locked by the process is correctly liberated using [lsof](https://man7.org/linux/man-pages/man8/lsof.8.html). Could we try this approach for **slapd**?

2021-05-21 06:17 UTC, juan131 commented on 2/debian-10/rootfs/opt/bitnami/scripts/libopenldap.sh
> +    if is_service_running "${pid}"; then
This shouldn't make any difference, right? I mean `is_ldap_running` is actually using `is_service_running` under the hood.

2021-05-21 06:18 UTC, juan131 requested changes
Sorry, I approved the PR by mistake.

2021-05-21 13:48 UTC, mattmoyer commented on 2/debian-10/rootfs/opt/bitnami/scripts/libopenldap.sh
> +    if is_service_running "${pid}"; then
Yes, but it's re-reading the PID file from disk each loop. I think the issue may be that the shutdown process of openldap deletes the PID file before it unlocks the database file. So even though the process is still running (shutting down), the `is_ldap_running` helper returns false (there's no PID file).

2021-05-24 09:58 UTC, juan131 approved these changes
LGTM! Thanks so much for implementing this approach

2021-05-24 10:44 UTC, juan131 commented
I'll send your code for internal review and keep you updated.

2021-05-24 13:01 UTC, juan131 commented
Your changes were approved/merged.

What's next? A new revision of the Bitnami OpenLDAP container (`2.4.58-debian-10-r62`) will be released within the next hours including your changes.

Thanks again for the contribution!

2021-05-24 13:01 UTC, merged