Fix Insufficient access in loading custom LDIF
bitnami/bitnami-docker-openldap pull request #77
Opened 2022-02-02 18:25 UTC by devent

This PR will differentiate between `*.config.ldif` and `*.ldif` files. For the first it will use the config admin and for the other the "normal" admin.

`*.config.ldif` shall include LDIFs that modify `dn: cn=module,cn=config`.

Fixes https://github.com/bitnami/bitnami-docker-openldap/issues/71

Don't know if you want to accept this solution or something else.

Changes only the initial LDIFs.

2022-02-03 13:09 UTC, fmulero requested changes
Hi @devent, Thank you so much for your PR. Please have look to the comments below. I have some changes suggested and a little doubt about how it works

Regards

2022-02-03 13:09 UTC, fmulero commented on 2.6/debian-10/rootfs/opt/bitnami/scripts/libopenldap.sh
> +        fi
I am not sure about the purpose of this block. If you have `LDAP_CONFIG_ADMIN_ENABLED=yes` then try to load the config files with the config user but if you don't have it, then it will use the old method, but it is not fully working as described in #71

2022-02-03 15:26 UTC, devent commented on 2.6/debian-10/rootfs/opt/bitnami/scripts/libopenldap.sh
> +        fi
I think this is the online configuration of OpenLDAP. So if you don't have `LDAP_CONFIG_ADMIN_ENABLED=yes` then you can't use LDIFs that modify `cn=config`.

2022-02-06 19:28 UTC, fmulero commented on 2.6/debian-10/rootfs/opt/bitnami/scripts/libopenldap.sh
> +        fi
I think this setup is a bit complicated and should be well documented. Also, we must take into account the hack explained in #71 what avoids setting all this configuration and allows modifications to `cn=config`, without adding any extra user. Keeping it in mind, I think we should simplify the solution and only set `-Y EXTERNAL` to the original code, but I am not sure if it has any other implication

2022-02-27 01:28 UTC, closed without merging